steps:
  javadoc:
    image: gradle:8.14.4-jdk17
    commands:
      - ./gradlew --no-daemon javadoc
  upload:
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      target: /config/data/docs/${CI_REPO}/${CI_COMMIT_BRANCH}
      source: build/docs/javadoc/
      strip_components: 3
